### ISSUE TITLE
请问为什么直接放行*.org

### ISSUE THREAD

**Issue by longmao365** [cxw620/AdGuard-Rules#10]
**规则39行的@@||*.org**

**Comment by cxw620** [comment]
主要是考虑到使用这个的广告/隐私收集追踪域名极少极少(至少在中国极少), 前面的通杀规则实测误杀了比较多的.org的域名, 当时更新频率可以到每天三更, (~~简单来说就是懒🤦‍♂️~~)干脆全部白名单了. 如果有发现漏杀的可以告诉我
