### ISSUE TITLE
目测部分软件企图通过内部DOH逃避DNS拦截

### ISSUE THREAD

**Issue by hacamer** [cxw620/AdGuard-Rules#11]
目测部分软件企图通过内部DOH逃避DNS拦截

今天没事看了下日志，发现部分httpdns已升级为与DoH一样的加密协议

如:

作业帮，域名`httpdns.zybang.com`

![image](https://user-images.githubusercontent.com/73057402/163573235-33f88fd3-9416-47b1-9cb1-555aff5b5df4.png)

爱奇艺，域名`doh.iqiyi.com`

![image](https://user-images.githubusercontent.com/73057402/163572966-58d05724-545c-4b16-b8cd-d75538a0934f.png)

只看了这两个，其他的未知

**Comment by cxw620** [comment]
这种还好, 拦截很简单, 我的规则考虑到这个, 有通配符拦截(拦截doh, dot, dns字样), httpdns也有针对ip的拦截.
但是缺点是有的, 例如bilibili, 有些app拦了httpdns直接用不了或者很久都加载不出来, 目测是app没有降级使用系统dns😅这个就让广告拦截显得鸡肋起来了.(也只有在APP才能这样, 要不然为什么都拼命推广APP砍掉网页端功能)
而且遇到微信那种连加载广告都用自有加密协议/mTLS双向验证的, 强行https过滤会直接让你没办法发信息, AdGuard也无能为力.
而且, 开AdGuard耗电也多了, 主要体现在移动端. 在这个以南极贱畜为首制造的这个乌烟瘴气的网络环境, 只能说, 🤔

**Comment by hacamer** [comment]
幾天前沒事看了下日誌（沒截圖）
忘記了是哪個APP，走的不是httpdns，走的是httpsdns🤔
域名為 `httpsdns.xxxx`
看來需要用關鍵詞攔截

**Comment by hacamer** [comment]
> 幾天前沒事看了下日誌（沒截圖） 忘記了是哪個APP，走的不是httpdns，走的是httpsdns🤔 域名為 `httpsdns.xxxx` 看來需要用關鍵詞攔截

關鍵詞大概是 `host*=` ` query`之類的

**Comment by cxw620** [comment]
> > 幾天前沒事看了下日誌（沒截圖） 忘記了是哪個APP，走的不是httpdns，走的是httpsdns🤔 域名為 `httpsdns.xxxx` 看來需要用關鍵詞攔截
> 
> 關鍵詞大概是 `host*=` ` query`之類的

确实, 这个我也收集了一部分

**Comment by cxw620** [comment]
但是, 正如我刚才说的, 有些app拦了httpdns直接用不了或者很久都加载不出来, 这就比较麻烦

**Comment by hacamer** [comment]
> 但是, 正如我刚才说的, 有些app拦了httpdns直接用不了或者很久都加载不出来, 这就比较麻烦

衹能單個實現精准攔截咯
