### ISSUE TITLE
能否对 img 做一个加白？

### ISSUE THREAD

**Issue by ghost** [cxw620/AdGuard-Rules#12]
快手d1-reco.a.kwimgs.com和d1-ec.a.kwimgs.com域名，CNAME响应域名中有个`dns`被AdGuard Home拦截了，技术太菜，不确定是不是误封，不过看到 img 我猜测应该是加载图片的域名。

另：很好的规则，可以提交给NextDNS吗？

**Comment by magicrw** [comment]
哦，我额外还想问一下：
||t*.pinduoduo.com^$important
我看了一下拼多多这一条规则拦截了以下域名：
tp.pinduoduo.com
tp-b.pinduoduo.com
th-a.pinduoduo.com
th.pinduoduo.com
这些域名是做什么用的？我的拦截记录里这些还挺多的

**Comment by cxw620** [comment]
> 哦，我额外还想问一下： ||t*.pinduoduo.com^$important 我看了一下拼多多这一条规则拦截了以下域名： tp.pinduoduo.com tp-b.pinduoduo.com th-a.pinduoduo.com th.pinduoduo.com 这些域名是做什么用的？我的拦截记录里这些还挺多的

猜测是广告追踪用的

**Comment by cxw620** [comment]
> d1-ec.a.kwimgs.com

这两个应该是加载广告图片的, 我看到别人的拦截规则也有这两个. 可以看一下有没有什么视频或者图片加载不出来. 不影响正常功能就行
img目前没发现几个误拦截的, 暂时不考虑加白
只有部分特异性强的可以提交, 像那些通杀的误杀比较多(虽然现在好很多了), 这个规则也是我自用拿来补充已有规则的

**Comment by magicrw** [comment]
> > d1-ec.a.kwimgs.com
> 
> 这两个应该是加载广告图片的, 我看到别人的拦截规则也有这两个. 可以看一下有没有什么视频或者图片加载不出来. 不影响正常功能就行 img目前没发现几个误拦截的, 暂时不考虑加白 只有部分特异性强的可以提交, 像那些通杀的误杀比较多(虽然现在好很多了), 这个规则也是我自用拿来补充已有规则的

确实没有太大影响，有时候我刷视频发现作者头像加载不出来，不过这种情况时有时无，我更怀疑是上游DNS的原因，因为我用的是国外DNS。主要是我用的软件少，也确实发现不了太多的误杀。

当然我还有一个建议就是对于那些系统级的跟踪，我的方案就是直接屏蔽这个公司的所有域名，在此贡献两个

#小米
||miui.com^$important
||mi.com^$important
/xiaomi/$important
||miwifi.com^$important
#华为
||hicloud.com^$important
##这个应该是高通的域名，我不知道为什么我的华为手机会链接它
||izatcloud.net^$important
/dbankcloud/
/huawei/

另外，对于一些记录 IP 的域名，我想也可以屏蔽

**Comment by magicrw** [comment]
> 这个规则也是我自用拿来补充已有规则的

天哪怎么只是补充，在我这里都是主力规则了

**Comment by cxw620** [comment]
> > > d1-ec.a.kwimgs.com
> > 
> > 
> > 这两个应该是加载广告图片的, 我看到别人的拦截规则也有这两个. 可以看一下有没有什么视频或者图片加载不出来. 不影响正常功能就行 img目前没发现几个误拦截的, 暂时不考虑加白 只有部分特异性强的可以提交, 像那些通杀的误杀比较多(虽然现在好很多了), 这个规则也是我自用拿来补充已有规则的
> 
> 确实没有太大影响，有时候我刷视频发现作者头像加载不出来，不过这种情况时有时无，我更怀疑是上游DNS的原因，因为我用的是国外DNS。主要是我用的软件少，也确实发现不了太多的误杀。
> 
> 当然我还有一个建议就是对于那些系统级的跟踪，我的方案就是直接屏蔽这个公司的所有域名，在此贡献两个
> 
> #小米 ||miui.com^$important ||mi.com^$important /xiaomi/$important ||miwifi.com^$important #华为 ||hicloud.com^$important ##这个应该是高通的域名，我不知道为什么我的华为手机会链接它 ||izatcloud.net^$important /dbankcloud/ /huawei/
> 
> 另外，对于一些记录 IP 的 API 域名，我想也可以屏蔽 ||api.ip.sb^$important 暂时就只有这个，之前也找到过其他的域名，但我的过滤规则丢过一次，所以没有了 我也尝试屏蔽过 ip geo 这类的关键词，误杀太大

屏蔽这个公司的所有域名这误杀太大了, 软件更新/云服务等这些必要功能就没法用了, 这个不值得.
拦截记录ip的api用处不大, 你访问对方的服务你肯定要暴露你的ip, 这些api一般是为了获取网络信息然后调度CDN什么的

**Comment by cxw620** [comment]
> > 这个规则也是我自用拿来补充已有规则的
> 
> 天哪怎么只是补充，在我这里都是主力规则了

我的readme已经写了😂主要是那些规则更新慢而且不全面, 我就补充了一点, 经历一个月的破坏性更新目前算是稳定期, 配合anti-AD等这些规则就基本没有漏杀的了

**Comment by magicrw** [comment]
> 软件更新/云服务等这些必要功能就没法用了, 这个不值得

我觉得用拦截广告规则的人大概都很注重隐私吧，拿我来说，云服务从来不用的，搜索引擎只用ddg，dns只用cloudflare，浏览器只用brave。甚至我还装了屏蔽所有google和微软域名的规则，也许是太激烈了吧😆

**Comment by cxw620** [comment]
> NextDNS有一个Beta功能就是拦截深度追踪，支持的品牌有华为 Windows 小米 苹果 啥的，它的规则相对没有我的那么激烈，但是我找不到他们的规则的链接

这东西人家拿来收钱的怎么可能暴露.

拦截深度追踪我个人觉得用处不大, 除非宁愿牺牲绝大部分的用户体验, 国内大环境就这样, 国外没去过, 国外软件没怎么用过, 不清楚. 理由如下
手机APP基本都用上了HTTPDNS或者HTTPSDNS, 关键域名不走系统DNS, 就算手机装个AdGuard之类的软件拦截了HTTPDNS或者HTTPSDNS, 如果软件适配不好, 回落到系统DNS不及时, 加载卡顿卡得怀疑人生, 同时AdGuard自身也耗电蛮厉害的, 广告拦截隐私追踪拦截就非常鸡肋了.
 
同时如微信这些美名其曰为了安全的软件还采用了自有的mmTLS,  等等,  根本拦截不了.

目前我的规则就是能用常规方法拦截的都尽力给拦截了, 少数极为奇葩(点名批评微信)的,就 算了. 好消息是, 目前已经可以关掉个性化推送了, 华为这些大厂商推进得比较好, 耐心设置一下就行.

个人认为在DNS层面的所谓深度拦截也不过是拼谁的规则更准确罢了, 花点时间抓个包分析分析, 或者黑盒法, 也是推断得出这个域名的作用的(我就是那么干的). 而且DNS层面的拦截在移动端显得远远不够, 原因就是HTTPDNS之类的东西, 还有就是有的域名混杂着请求必要内容和请求广告. 要不然怎么都砍掉网页端的功能, 把用户赶到APP上去

个人看法, APP还不如PWA

**Comment by cxw620** [comment]
> > 软件更新/云服务等这些必要功能就没法用了, 这个不值得
> 
> 我觉得用拦截广告规则的人大概都很注重隐私吧，拿我来说，云服务从来不用的，搜索引擎只用ddg，dns只用cloudflare，浏览器只用brave。甚至我还装了屏蔽所有google和微软域名的规则，也许是太激烈了吧😆

确实有点激烈😀, 不过归根究底, 互联网时代不存在什么隐私, 我也是在尽力不影响到个人使用查资料等等的前提下去拦截广告的

**Comment by cxw620** [comment]
> > 软件更新/云服务等这些必要功能就没法用了, 这个不值得
> 
> 我觉得用拦截广告规则的人大概都很注重隐私吧，拿我来说，云服务从来不用的，搜索引擎只用ddg，dns只用cloudflare，浏览器只用brave。甚至我还装了屏蔽所有google和微软域名的规则，也许是太激烈了吧😆

我个人只是非常讨厌那些奇奇怪怪的广告, 隐私嘛, 能保护一点是一点吧
