### ISSUE TITLE
twitter图片和视频无法显示.

### ISSUE THREAD

**Issue by kiddin9** [cxw620/AdGuard-Rules#4]
![image](https://user-images.githubusercontent.com/48883331/148507128-6a3af812-e78b-4cfd-8b08-434a45dfc0e1.png)

**Comment by cxw620** [comment]
主要是*dns*这个误拦截太多了（本意是拦截可能的HTTPDNS还有DoT或者DoH避免拦截失效）。如果主力是用电脑端，建议在自定义规则里加一个@@*dns*。
现在我就把那个CDN加白名单。

**Comment by kiddin9** [comment]
还得加上 @@||ecdns.net^ 不然还是打不开.

**Comment by cxw620** [comment]
OK，感谢反馈
