### ISSUE TITLE
gw.alipayobjects.com误杀

### ISSUE THREAD

**Issue by kiddin9** [cxw620/AdGuard-Rules#5]
https://github.com/cxw620/AdGuard-Rules/blob/f507640d59ca5624126f0e235d92fc642016c4c2/wjx-AdGuardHome-blocklist.txt#L27
这个网站不能屏蔽, 很多网站需要用到这个网站里的库, 比如 https://gw.alipayobjects.com/os/lib/react/16.13.1/umd/react.production.min.js

**Comment by cxw620** [comment]
ok，收到

**Comment by cxw620** [comment]
已更新
