### ISSUE TITLE
playstation相关域名全部误杀

### ISSUE THREAD

**Issue by SuSpoiled** [cxw620/AdGuard-Rules#8]
stat、dns，甚至是ads都有大量误杀，基本所有关键词都需要一个庞大的白名单来进行维护。

**Comment by cxw620** [comment]
确实，为了强力拦截当初加入这三个通杀，不过误杀非常多，考虑到这问题，我将把通杀的这三个独立出去一个文件，然后关注这通杀的拦截情况实时增加白名单以及常规拦截文件的黑名单。

**Comment by cxw620** [comment]
> stat、dns，甚至是ads都有大量误杀，基本所有关键词都需要一个庞大的白名单来进行维护。

目前已经独立出去，预计一周内迭代新版本

**Comment by SuSpoiled** [comment]
> > stat、dns，甚至是ads都有大量误杀，基本所有关键词都需要一个庞大的白名单来进行维护。
> 
> 目前已经独立出去，预计一周内迭代新版本

辛苦了！很难找到一个关注了HTTPDNS解析广告的列表！

**Comment by cxw620** [comment]
> > > stat、dns，甚至是ads都有大量误杀，基本所有关键词都需要一个庞大的白名单来进行维护。
> > 
> > 
> > 目前已经独立出去，预计一周内迭代新版本
> 
> 辛苦了！很难找到一个关注了HTTPDNS解析广告的列表！

目前除了微信其他的都还好，存在HTTPDNS的我都单列出来在AdGuard上面拦截了，主要是考虑到减少手机端的规则数量减少耗电。微信的没办法开HTTPS强制过滤，一开健康码这些就用不了了，拦截效果大打折扣，微信可谓真毒瘤
