### ISSUE TITLE
可以分享下你那边用的那些规则吗？

### ISSUE THREAD

**Issue by owedocker** [cxw620/AdGuard-Rules#9]
具体下

**Comment by cxw620** [comment]
```
AdGuard, AdGuardHome内置的全部
Easylist全家族
AdBlock全家族
trli收集的规则 -> https://github.com/Potterli20/hosts
BlueSkyXN收集的规则集
CatsTeam收集的规则集 -> https://github.com/Cats-Team/AdRules 
neoFelhz收集的规则集 -> https://github.com/neoFelhz/neohosts
halflife收集的规则集 -> https://github.com/o0HalfLife0o/list
cjx82630收集的规则集 -> https://github.com/cjx82630/cjxlist
```
就这些(2022/07/25更新)

**Comment by cxw620** [comment]
欢迎补充

**Comment by hacamer** [comment]
部分链接已失效，注意更新

> ```
> AdGuard, AdGuardHome内置的全部
> Easylist全家族
> AdBlock全家族
> trli收集的规则 -> https://trli.coding.net/p/file/d/ad-hosts/git/lfs/master/ad-adguardhome.txt
> BlueSkyXN收集的规则集
> CatsTeam收集的规则集 -> https://cats-team.coding.net
> https://cdn.jsdelivr.net/gh/neoFelhz/neohosts@gh-pages/full/hosts.txt
> https://cdn.jsdelivr.net/gh/lhbill/xiaomiad@master/xiaomi.txt
> halflife收集的规则集 -> https://gitee.com/halflife/
> https://gitee.com/cjx82630/cjxlist/raw/master/cjxlist.txt
> ```
> 
> 就这些

**Comment by cxw620** [comment]
> 部分链接已失效，注意更新
> 
> > ```
> > AdGuard, AdGuardHome内置的全部
> > Easylist全家族
> > AdBlock全家族
> > trli收集的规则 -> https://trli.coding.net/p/file/d/ad-hosts/git/lfs/master/ad-adguardhome.txt
> > BlueSkyXN收集的规则集
> > CatsTeam收集的规则集 -> https://cats-team.coding.net
> > https://cdn.jsdelivr.net/gh/neoFelhz/neohosts@gh-pages/full/hosts.txt
> > https://cdn.jsdelivr.net/gh/lhbill/xiaomiad@master/xiaomi.txt
> > halflife收集的规则集 -> https://gitee.com/halflife/
> > https://gitee.com/cjx82630/cjxlist/raw/master/cjxlist.txt
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
更新了

**Comment by hacamer** [comment]
补充 halflife的规则集 为 https://github.com/o0HalfLife0o/list
这是原作者
